### ISSUE TITLE
Can't load Nether chunks

### ISSUE THREAD

**Issue by TaylorDale** [PrismarineJS/bedrock-provider#14]
Nether chunks appear to have no block data:
![image](https://user-images.githubusercontent.com/5500716/149448513-a41fb18b-8e26-4816-8035-55b3efb93f4c.png)

Using the following code:
```
async function load(folder, dimension = 1) {
  const db = new LevelDB(locDB, {
    createIfMissing: false,
  });
  await db.open();
  const world = new WorldProvider(db, { dimension });
  return { db, world };
}

async function getChunk(world, xx, zz) {
  const has = await world.hasChunk(xx, zz);
  if (!has) {
    console.warn(`WARNING: No chunk found at ${xx}, ${zz}`);
    return undefined;
  }
  return world.load(xx, zz, true);
}
```

The world I'm using definitely has disk-written Nether chunks, I can load up the world and see changes etc. where I am trying to read them.

Any clues?

**Comment by extremeheat** [comment]
Can you provide the output of `.getKeys()` in world provider? It's possible the nether chunks were just not serialized to disk. Minecraft bedrock edition will only write chunks to disk if they have changed since chunk generation--so make sure that the chunk data has changed in some way.

**Comment by TaylorDale** [comment]
I will get you that output shortly - I've made modifications by hand on the server before closing the server gracefully, and used repair() on the db (if that makes a difference). Have also loaded the world back up after to confirm changes are there.

I'll upload a save file/small demo if you'd like to replicate it

**Comment by TaylorDale** [comment]
This is what I'm getting from getKeys() 
https://pastebin.com/S9zrUmus

**Comment by extremeheat** [comment]
Try loading a world at {"x":-1,"z":-3,"dim":1

**Comment by TaylorDale** [comment]
Seems to have entity datas but sections is still [] 
https://pastebin.com/0WnkrBYn

**Comment by TaylorDale** [comment]
Demo
[mcdemo.zip](https://github.com/PrismarineJS/bedrock-provider/files/7885957/mcdemo.zip)
:

**Comment by rom1504** [comment]
can you try again now @TaylorDale ? major changes have been done

**Comment by TaylorDale** [comment]
Yep I'll re-run the tests today. Thanks

**Comment by TaylorDale** [comment]
Just looking at it now, getting:

Chunk x: -1, z: -3
.sections length === 0

new package.json:
```
{
  "name": "mcdemo",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "bedrock-provider": "^2.2.0",
    "leveldb-zlib": "^1.2.0"
  }
}
```

cheers
