### ISSUE TITLE
Support Caves and Cliffs

### ISSUE THREAD

**Issue by ATXLtheAxolotl** [PrismarineJS/bedrock-provider#8]

**Comment by TaylorDale** [comment]
Is 1.18 supported with the  2.0.0 release? I'm still getting subchunk count = -1 in the level_chunk event (I note there is a comment to say this is for loading biomes, but I don't get any subchunk_count > -1).

**Comment by ATXLtheAxolotl** [comment]
Not really sure. I think the latest commit adds some 1.18 functionality though.

**Comment by TaylorDale** [comment]
Hmm still getting sub_chunk_count:-1 with 2.1.0 unfortunately. Any ideas?

**Comment by extremeheat** [comment]
1.18 level format is now supported here, and there are examples for on-disk support in this repo. For network support the chunk fetching procedure has changed and depending on how the server wants to provide chunks (there are about 4 ways to do this now...), the client may have to raycast and request data for the individual subchunks that it needs opposed to the server sending everything in one packet. Will be implemented inside of mineflayer, progress can be tracked in https://github.com/PrismarineJS/bedrock-protocol/issues/116

**Comment by TaylorDale** [comment]
Interesting, thanks. So essentially there is now a client request command that would take parameters like {cX, cY, cZ, subIdx} ?
